package dev.aura.powermoney.client.helper;

import dev.aura.powermoney.PowerMoney;
import dev.aura.powermoney.PowerMoneyBlocks;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import lombok.AccessLevel;
import lombok.Getter;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.ItemStack;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

@SuppressFBWarnings(
  value = {"RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE", "JLM_JSR166_UTILCONCURRENT_MONITORENTER"},
  justification = "Code is generated by lombok which means I don't have any influence on it."
)
public class PowerMoneyCreativeTab extends CreativeTabs {
  @Getter(value = AccessLevel.PRIVATE, lazy = true)
  private final ItemStack iconItem = new ItemStack(PowerMoneyBlocks.powerReceiver());

  public PowerMoneyCreativeTab() {
    super(PowerMoney.ID);
  }

  @Override
  @SideOnly(Side.CLIENT)
  public ItemStack createIcon() {
    return getIconItem();
  }
}
